Доработана функциональность по техническому заданию спринта
Omorlan/java-kanban pull request #4
Opened 2024-03-17 18:07 UTC by Omorlan

feat: Заменить множества циклов на лямбды
feat: Добавить задачам даты
feat: Добавить новые тесты

2024-03-18 13:37 UTC, afomkina requested changes
Нужно немного доработать тесты, чтобы они соответствовали тз: 
```
Для двух менеджеров задач InMemoryTaskManager и FileBackedTaskManager.
a. Чтобы избежать дублирования кода, нужен базовый класс с тестами на каждый метод из интерфейса abstract class TaskManagerTest<T extends TaskManager>.
b. Для подзадач нужно дополнительно проверить наличие эпика, а для эпика — расчёт статуса.
c. Добавить тест на корректность расчёта пересечения интервалов.
```
Выше пунтк тз, который сейчас реализован не до конца. Нужно создать абстрактный класс `TaskManagerTest<T extends TaskManager>`, где будут реализованы базовые тесты для каждого метода `TaskManager` (сейчас у тебя это сделано только в `InMemoryTaskManagersTest`). Этот абстрактный класс должны наследовать `FileBackedTaskManagerTest` и `InMemoryTaskManagersTest`, соотвественно данные тесты будут запускаться и для `InMemoryTaskManagersTest` и для `FileBackedTaskManagerTest`, а не только для `InMemoryTaskManagersTest`, как у тебя есть сейчас. Отдельно в `FileBackedTaskManagerTest` должны остаться тесты сохранения и загрузки из файла.

Нужно максимально избавиться от дублирования в тестах, используй [@BeforeEach/@AfterEach](https://habr.com/ru/articles/590699/), чтобы создать объекты, которые используются во всех тестах класса/вынести повторяющиеся действия; 
[@ParameterizedTest](https://www.baeldung.com/parameterized-tests-junit-5), если тесты делают одни и теже проверки, но отличаются только проверяемые объекты


И еще момет - сейчас отсутствуют библиотеки с тестами, чтобы корректно можно было запустить тесты с любой машины. Так в файле `.gitignore` прописано правило игнорирования файлов типа `*.class`, все библиотеки игнорируются гитом и не добавляются в удаленный репозиторий. Нужно удалить строчку `*.class` и закоммитить библиотеки

2024-03-18 13:37 UTC, afomkina commented on src/Main.java
> +       System.out.println(manager2.getHistory());
Поехала разметка, чтобы быстро поправить проще всего использовать сочетание клавиш [Ctrl+Alt+L](https://www.jetbrains.com/idea/guide/tips/reformat-file/) в Idea. Оно позволяет быстро подогнать код к корректной разметке

2024-03-18 13:37 UTC, afomkina commented on src/sprint/managers/taskmanager/InMemoryTaskManager.java
> +    protected Set<Task> prioritizedTasks = new TreeSet<>();
Сейчас ты создаешь упорядоченную коллекцию с несравнимыми элементами. Рекомендуется либо реализовать интерфейс [Comparable](https://vertex-academy.com/tutorials/ru/interfejsy-comparable-comparator-java/) для класса `Task`, либо предоставить пользовательский `Comparator` при создании `TreeSet`, чтобы коллекция сортировалась корректно

2024-03-18 13:37 UTC, afomkina commented on src/sprint/managers/taskmanager/InMemoryTaskManager.java
> +        prioritizedTasks = new TreeSet<>(Comparator.comparing(Task::getStartTime,
Соответсвенно тут создавать новую коллекцию тут будет не нужно.

2024-03-18 13:37 UTC, afomkina commented on src/sprint/managers/taskmanager/InMemoryTaskManager.java
> +                .map(subTaskId -> subTaskMap.get(subTaskId))
Можно заменить на [method reference](https://www.baeldung.com/java-method-references), так код выглядит лаконичнее
```suggestion
                .map(subTaskMap::get)
```

2024-03-18 13:37 UTC, afomkina commented on src/sprint/managers/taskmanager/TaskManager.java
> +         a. ��������� ������ ���� �����.
Поехала кодировка

2024-03-18 13:37 UTC, afomkina commented on test/src/managers/historymanager/InMemoryHistoryManagersTest.java
> +        Task task6 = new Task("Task 6", "DescriptionTask", TaskStatus.IN_PROGRESS, 10, "17.03.2024 17:05");
Можно создать нужное количество задач в цикле, затем создать их в менеджере задач и добавить в менеджер истории. После нужно будет проверить, что размер коллекции соответсвует колличеству созданных задач, а потом удалить одну и проверить, что размер уменьшился на 1. 
В коммерческой разработке принято максимально избавляться от дублирований, такой код считается "грязным"

2024-03-18 13:37 UTC, afomkina commented on test/src/managers/historymanager/InMemoryHistoryManagersTest.java
> +        Task task2 = new Task("Task 2", "DescriptionTask", TaskStatus.IN_PROGRESS, 10, "17.03.2024 16:21");
Чтобы проверить дублирования, достаточно одной задачи

2024-03-18 14:09 UTC, Omorlan commented on test/src/managers/historymanager/InMemoryHistoryManagersTest.java
> +        Task task2 = new Task("Task 2", "DescriptionTask", TaskStatus.IN_PROGRESS, 10, "17.03.2024 16:21");
не могу согласиться, так я проверяю и что таска не продублировалась и что осталось ее последнее вхождение
т.е. чтобы не было ситуации Task1,Task2<-Task1 = Task1,Task2,Task1, либо = Task1,Task2

2024-03-19 17:04 UTC, Omorlan commented on test/src/managers/historymanager/InMemoryHistoryManagersTest.java
> +        Task task2 = new Task("Task 2", "DescriptionTask", TaskStatus.IN_PROGRESS, 10, "17.03.2024 16:21");
В целом это проверялось в addAndGetHistoryShouldReturnCorrectHistory поэтому удалил его

2024-03-19 19:31 UTC, Omorlan commented on src/Main.java
> +       System.out.println(manager2.getHistory());
Поправил, комбинацию знаю просто завтыкал :C

2024-03-19 19:31 UTC, Omorlan commented on src/sprint/managers/taskmanager/InMemoryTaskManager.java
> +    protected Set<Task> prioritizedTasks = new TreeSet<>();
Поправил, Спасибо

2024-03-19 19:32 UTC, Omorlan commented on test/src/managers/historymanager/InMemoryHistoryManagersTest.java
> +        Task task6 = new Task("Task 6", "DescriptionTask", TaskStatus.IN_PROGRESS, 10, "17.03.2024 17:05");
Поправил, я считаю что я ловко переоформил всю эту систему, лично я собой доволен теперь

2024-03-20 00:56 UTC, afomkina requested changes
Тесты здорово получились, молодец 🔥

2024-03-20 00:56 UTC, afomkina commented on test/src/managers/TaskManagerTest.java
> +    static Stream<TaskStatus[]> provideSubTaskStatusCombinations() {
Методам со строк 48 и 54 нужно добавить модификаторы доступа, так как они используются только внутри данного класса

2024-03-20 00:56 UTC, afomkina commented on test/src/managers/historymanager/InMemoryHistoryManagersTest.java
>      HistoryManager historyManager = Managers.getDefaultHistory();
У полей класса не хватает модифкаторов доступа

2024-03-20 00:56 UTC, afomkina commented on test/src/managers/historymanager/InMemoryHistoryManagersTest.java
> +    void genTasks(int amount, String type) {
Метод дублируется в `TaskManagerTest`, лучше вынести его в отдельный утильный файл и переиспользовать

2024-03-20 16:13 UTC, afomkina approved these changes

2024-03-21 07:38 UTC, merged