Доработана функциональность по техническому заданию спринта
Omorlan/java-kanban pull request #5
Opened 2024-03-30 09:37 UTC by Omorlan

feat: Добавить обработку сетевых запросов
feat: Добавить тесты под новый функционал

2024-03-30 09:41 UTC, Omorlan commented
![review](https://github.com/Omorlan/java-kanban/assets/140850406/b033ceb9-1f42-4346-960d-86077d4cf9a2)

2024-03-31 15:30 UTC, afomkina commented on src/server/adapter/LocalDateTimeAdapter.java
> +    private final DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("dd.MM.yyy HH:mm");
Лучше вынести паттерн в отдельный утильный класс и сделать константой, чтобы можно было переиспользовать его в нескольких классах

2024-03-31 15:54 UTC, afomkina requested changes

2024-03-31 15:54 UTC, afomkina commented on test/src/server/HttpTaskServerTest.java
> +    HttpTaskServer taskServer;
У некоторых полей класса не хватает модификатора доступа

2024-03-31 15:54 UTC, afomkina commented on test/src/server/HttpTaskServerTest.java
> +    POST
Предлагаю немного подекомпозировать тесты и разбить из на логические составляющие. Это можно сделать с помощью [@Nested классов](https://www.petrikainulainen.net/programming/testing/junit-5-tutorial-writing-nested-tests/). Так код станет более читаемым и его будет проще поддерживать

2024-03-31 15:54 UTC, afomkina commented on src/server/handler/EpicsHandler.java
> +            exception.printStackTrace();
Лучше не печатать стектрейс, а логировать мессадж ошибки:
`System.out.print(exception.getMessage());`
Чаще всего весь стектрейс нам не нужен(он большой и малоинформативный), а достаточного всего лишь сообщения

2024-03-31 15:54 UTC, afomkina commented on src/server/handler/HistoryHandler.java
> +            exception.printStackTrace();
Лучше просто распечатать мессадж исключения

2024-03-31 15:54 UTC, afomkina commented on src/server/handler/PrioritizedHandler.java
> +            exception.printStackTrace();
И здесь

2024-03-31 15:54 UTC, afomkina commented on src/server/handler/SubtasksHandler.java
> +            exception.printStackTrace();
И здесь

2024-03-31 15:54 UTC, afomkina commented on src/server/handler/SubtasksHandler.java
> +                        String pathId = path.replaceFirst(SUBTASKS, "");
Код со строк 91-99 повторяется в классе `TasksHandler` на строках 90-98. Нужно выделить его в отдельный метод  с сигнатурой
`protected String yourName(String path, String url, HttpExchange exchange) throws IOException`
в классе `Handler` и переиспользовать, а не дублировать

2024-03-31 15:54 UTC, afomkina commented on src/server/handler/SubtasksHandler.java
> +                            id = parsePathId(pathId);
Переменная id нигде не используется, ее нужно либо использовать, либо удалить

2024-03-31 15:54 UTC, afomkina commented on src/server/handler/SubtasksHandler.java
> +                            exchange.sendResponseHeaders(500, 0);
Задание со `"*"`:
Можно создать отдельное перечисление для HTTP кодов и использовать его вместо "голых" цифр. 
Так код будет выглядеть более читаемо и понятней. 
Примеры можно посмотреть в главе [Конструкторы, поля и методы перечисления](https://metanit.com/java/tutorial/3.8.php#:~:text=%D0%9A%D0%BE%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D0%BE%D1%80%D1%8B%2C%20%D0%BF%D0%BE%D0%BB%D1%8F%20%D0%B8%20%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%8B%20%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F)

2024-03-31 16:33 UTC, Omorlan commented on src/server/handler/SubtasksHandler.java
> +                            exchange.sendResponseHeaders(500, 0);
чтож я был готов и к этому
![изображение_2024-03-31_193317662](https://github.com/Omorlan/java-kanban/assets/140850406/ab075b6e-cf74-40cb-9e4c-5895e30b430d)

2024-03-31 17:03 UTC, Omorlan commented on test/src/server/HttpTaskServerTest.java
> +    POST
надеюсь я правильно понял концепцию

2024-03-31 17:40 UTC, Omorlan commented on src/server/handler/SubtasksHandler.java
> +                            id = parsePathId(pathId);
убрав id, пропала и проблема с дублированием

2024-04-01 13:10 UTC, afomkina approved these changes
Получилось здорово, молодец 🔥

2024-04-01 13:10 UTC, afomkina commented on src/resources/HttpStatusCode.java
> +public enum HttpStatusCode {
🔥

2024-04-01 13:10 UTC, afomkina commented on src/resources/UtilConstant.java
> +public class UtilConstant {
🔥

2024-04-02 12:59 UTC, merged